

name: 'data_pipeline'
version: '1.0.0'

profile: 'data_pipeline'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  data_pipeline:
    staging:
      +materialized: view
      snowflake_warehouse: dbt_wh
      
    intermediate:
      +materialized: table
      snowflake_warehouse: dbt_wh

    marts:
      +materialized: table
      snowflake_warehouse: dbt_wh

